newline_style               = "Unix"
wrap_comments               = true
format_code_in_doc_comments = true
normalize_comments          = true
normalize_doc_attributes    = true
format_strings              = true
format_macro_matchers       = true
hex_literal_case            = "Lower"
struct_lit_single_line      = false
imports_granularity         = "Crate"
group_imports               = "StdExternalCrate"
reorder_impl_items          = true
overflow_delimited_expr     = true
match_arm_blocks            = false
trailing_semicolon          = true
match_block_trailing_comma  = true
blank_lines_upper_bound     = 2
edition                     = "2021"
style_edition               = "2021"
use_try_shorthand           = true
use_field_init_shorthand    = true
condense_wildcard_suffixes  = true
unstable_features           = true
